(library
 (name common)
 (modules common)
 (libraries why3)
)
(library
 (name env)
 (libraries re ppxlib elpi elpi_api_compat why3 common)
 (modules env)
 (preprocess (pps ppx_elpi))
 (ppx_runtime_libraries elpi elpi_api_compat)
)
(library
 (name ty)
 (libraries re ppxlib elpi elpi_api_compat why3 common)
 (modules ty)
 (preprocess (pps ppx_elpi))
 (ppx_runtime_libraries elpi elpi_api_compat)
)
(library
 (name term)
 (libraries re ppxlib elpi elpi_api_compat why3 ty common)
 (modules term)
 (preprocess (pps ppx_elpi))
 (ppx_runtime_libraries elpi elpi_api_compat)
)
(library
 (name decl)
 (libraries re ppxlib elpi elpi_api_compat why3 common term ty)
 (modules decl)
 (preprocess (pps ppx_elpi))
 (ppx_runtime_libraries elpi elpi_api_compat)
)
(library
 (name theory)
 (libraries re ppxlib elpi elpi_api_compat why3 common decl)
 (modules theory)
 (preprocess (pps ppx_elpi))
 (ppx_runtime_libraries elpi elpi_api_compat)
)
(library
 (name task)
 (libraries re ppxlib elpi elpi_api_compat why3 theory)
 (modules task)
 (preprocess (pps ppx_elpi))
 (ppx_runtime_libraries elpi elpi_api_compat)
)