(library
 (name common)
 (modules common)
 (libraries why3)
)
(library
 (name env)
 (libraries elpi why3 common)
 (modules env)
 (preprocess (pps ppx_elpi))
)
(library
 (name ty)
 (libraries elpi why3 common)
 (modules ty)
 (preprocess (pps ppx_elpi))
)
(library
 (name term)
 (libraries elpi elpi.runtime why3 ty common)
 (modules term)
 (preprocess (pps ppx_elpi))
)
(library
 (name decl)
 (libraries elpi why3 common term ty)
 (modules decl)
 (preprocess (pps ppx_elpi))
)
(library
 (name theory)
 (libraries elpi why3 common decl)
 (modules theory)
 (preprocess (pps ppx_elpi))
)
(library
 (name task)
 (libraries elpi why3 theory term)
 (modules task)
 (preprocess (pps ppx_elpi))
)
