(* This is based on code generated by the PPX, *)
open Common
open Why3
open Why3.Ty

let declaration = ref []
type tysymbol = Why3.Ty.tysymbol
[@@elpi.opaque {
  name = "tysymbol";
  doc = "Embedding of type symbols. Internal information (Ident, arguments) is not exposed.";
  pp = pp_why_data Pretty.print_ts;
  compare = Ty.ts_compare;
  hash = Hashtbl.hash;
  hconsed = false;
  constants = [("arr", Ty.ts_func)];
}]
[@@deriving elpi {declaration}]

type tvsymbol = Why3.Ty.tvsymbol
[@@elpi.opaque {
  name = "tvsymbol";
  doc = "Embedding of type variables. Internal information (Ident, arguments) is not exposed.";
  pp = pp_why_data Pretty.print_tv;
  compare = Ty.tv_compare;
  hash = Hashtbl.hash;
  hconsed = false;
  constants = [];
}]
[@@deriving elpi {declaration}]

type why_simple_ty =
| Tyvar of tvsymbol
| Tyapp of tysymbol * why_simple_ty list
[@@deriving elpi {declaration}]
[@@elpi.type_code "ty"]
[@@elpi.pp fun fmt _ -> Format.fprintf fmt "<ty>"]

let rec ty_to_why_simple_ty (t : Ty.ty) : why_simple_ty =
  match t.ty_node with | Tyvar v -> Tyvar v | Tyapp (t, a) -> Tyapp (t, (List.map ty_to_why_simple_ty a))

let rec why_simple_ty_to_ty (t : why_simple_ty) : Ty.ty =
  match t with | Tyvar v -> Ty.ty_var v | Tyapp (t, a) -> Ty.ty_app t (List.map why_simple_ty_to_ty a)

let ty : 'c 'csts .  (ty, 'c, 'csts) Elpi.API.ContextualConversion.t =
let open Elpi.API.ContextualConversion in
  let kind = TyName "ty" in
  {ty = kind;
   pp_doc = why_simple_ty.pp_doc;
   pp = Pretty.print_ty;
   embed = (fun ~depth h c s t -> elpi_embed_why_simple_ty ~depth h c s (ty_to_why_simple_ty t));
   readback = (fun ~depth h c s t -> let (a,b,c) = elpi_readback_why_simple_ty ~depth h c s t in (a, why_simple_ty_to_ty b, c))
  }