(* This is based on code generated by the PPX, *)
open Common
open Why3
open Why3.Ty

let declaration = ref []
let elpi_opaque_data_decl_tysymbol = Elpi.API.OpaqueData.declare {
  name = "tysymbol";
  doc = "Embedding of type symbols. Internal information (Ident, arguments) is not exposed.";
  pp = pp_why_data Pretty.print_ts;
  compare = Ty.ts_compare;
  hash = Hashtbl.hash;
  hconsed = false;
  constants = [("arr", Ty.ts_func)] (* [("«ts_int»", Ty.ts_int ); ("«ts_real»", Ty.ts_real ); ("«ts_bool»", Ty.ts_bool ); ("«ts_str»", Ty.ts_str )] *);
}
module Ctx_for_tysymbol =
  struct
    class type t = object inherit Elpi.API.ContextualConversion.ctx end
  end
let tysymbol : 'c .  (tysymbol, #Elpi.API.ContextualConversion.ctx as 'c, 'csts) Elpi.API.ContextualConversion.t =
  let { Elpi.API.Conversion.embed = embed; readback; ty; pp_doc; pp } =
    elpi_opaque_data_decl_tysymbol in
  let embed ~depth  _ _ s t = embed ~depth s t in
  let readback ~depth  _ _ s t = readback ~depth s t in
  { Elpi.API.ContextualConversion.embed = embed; readback; ty; pp_doc; pp }
let elpi_embed_tysymbol = tysymbol.Elpi.API.ContextualConversion.embed
let elpi_readback_tysymbol = tysymbol.Elpi.API.ContextualConversion.readback
let elpi_tysymbol = Elpi.API.BuiltIn.MLDataC tysymbol
class ctx_for_tysymbol (h : Elpi.API.Data.hyps)  (_s : Elpi.API.Data.state) : Ctx_for_tysymbol.t =
  object (_) inherit  ((Elpi.API.ContextualConversion.ctx) h) end
let (in_ctx_for_tysymbol : (Ctx_for_tysymbol.t, 'csts) Elpi.API.ContextualConversion.ctx_readback) =
      fun ~depth:_ h c s -> (s, ((new ctx_for_tysymbol) h s), c, (List.concat []))
let () = declaration := !declaration @ [elpi_tysymbol]
(* let ciao (t : tysymbol) =
  match t with | { ts_name; ts_args; ts_def } -> (match ts_def with | NoDef -> _ | Alias _ -> _ | Range _ -> _ | Float _ -> _) *)
let elpi_opaque_data_decl_tvsymbol = Elpi.API.OpaqueData.declare {
  name = "tvsymbol";
  doc = "Embedding of type variables. Internal information (Ident, arguments) is not exposed.";
  pp = pp_why_data Pretty.print_tv;
  compare = Ty.tv_compare;
  hash = Hashtbl.hash;
  hconsed = false;
  constants = [];
}
module Ctx_for_tvsymbol =
  struct
    class type t = object inherit Elpi.API.ContextualConversion.ctx end
  end
let tvsymbol : 'c .  (tvsymbol, #Elpi.API.ContextualConversion.ctx as 'c, 'csts) Elpi.API.ContextualConversion.t =
  let { Elpi.API.Conversion.embed = embed; readback; ty; pp_doc; pp } =
    elpi_opaque_data_decl_tvsymbol in
  let embed ~depth  _ _ s t = embed ~depth s t in
  let readback ~depth  _ _ s t = readback ~depth s t in
  { Elpi.API.ContextualConversion.embed = embed; readback; ty; pp_doc; pp }
let elpi_embed_tvsymbol = tvsymbol.Elpi.API.ContextualConversion.embed
let elpi_readback_tvsymbol = tvsymbol.Elpi.API.ContextualConversion.readback
let elpi_tvsymbol = Elpi.API.BuiltIn.MLDataC tvsymbol
class ctx_for_tvsymbol (h : Elpi.API.Data.hyps)  (_s : Elpi.API.Data.state) : Ctx_for_tvsymbol.t =
  object (_) inherit  ((Elpi.API.ContextualConversion.ctx) h) end
let (in_ctx_for_tvsymbol : (Ctx_for_tvsymbol.t, 'csts) Elpi.API.ContextualConversion.ctx_readback) =
      fun ~depth:_ h c s -> (s, ((new ctx_for_tvsymbol) h s), c, (List.concat []))
let () = declaration := !declaration @ [elpi_tvsymbol]

type why_simple_ty =
| Tyvar of tvsymbol
| Tyapp of tysymbol * why_simple_ty list
[@@deriving elpi {declaration}]
[@@elpi.type_code "ty"]
[@@elpi.pp fun fmt _ -> Format.fprintf fmt "<ty>"]

let rec ty_to_why_simple_ty (t : Ty.ty) : why_simple_ty =
  match t.ty_node with | Tyvar v -> Tyvar v | Tyapp (t, a) -> Tyapp (t, (List.map ty_to_why_simple_ty a))

let rec why_simple_ty_to_ty (t : why_simple_ty) : Ty.ty =
  match t with | Tyvar v -> Ty.ty_var v | Tyapp (t, a) -> Ty.ty_app t (List.map why_simple_ty_to_ty a)

let ty : 'c 'csts .  (ty, #Ctx_for_why_simple_ty.t as 'c, 'csts) Elpi.API.ContextualConversion.t =
let open Elpi.API.ContextualConversion in
  let kind = TyName "ty" in
  {ty = kind;
   pp_doc = why_simple_ty.pp_doc;
   pp = Pretty.print_ty;
   embed = (fun ~depth h c s t -> elpi_embed_why_simple_ty ~depth h c s (ty_to_why_simple_ty t));
   readback = (fun ~depth h c s t -> let (a,b,c) = elpi_readback_why_simple_ty ~depth h c s t in (a, why_simple_ty_to_ty b, c))
  }