(cram
 (deps
  (glob_files *.mlw)
  why3extra.test.conf
  normalize_quantifiers
  check_open_term_attrs.elpi
  ../examples/apply_lite.elpi
  ../examples/apply_ho.elpi
  ../examples/assert.elpi
  ../examples/case.elpi
  ../examples/destruct.elpi
  ../examples/exists_term.elpi
  ../examples/derive.elpi
  ../examples/derive_eq.elpi
  ../examples/drop_non_goal_props.elpi
  ../examples/intro_implies.elpi
  ../examples/intros_full.elpi
  ../examples/intros_full_local.elpi
  ../examples/open_forall_ctx.elpi
  ../examples/rebuild_case.elpi
  ../examples/rebuild_case_as.elpi
  ../examples/split_goal_and.elpi
  ../examples/tc.elpi
  ../transform.elpi
  ../bin/why3_elpi_transformations.cmxs))

(rule
 (alias replay)
 (deps
  why3extra.test.conf
  ../w3lp.elpi
  ../transform.elpi
  ../examples/apply_ho.elpi
  ../examples/assert.elpi
  ../examples/destruct.elpi
  sessions/search.mlw
  sessions/search/why3session.xml
  sessions/quicksort.mlw
  sessions/quicksort/why3session.xml
  sessions/drinker.mlw
  sessions/drinker/why3session.xml
  ../bin/why3_elpi_transformations.cmxs)
 (action
  (progn
   (run why3 config detect)
   (run why3 replay --extra-config why3extra.test.conf sessions/search)
   (run why3 replay --extra-config why3extra.test.conf sessions/quicksort)
   (run why3 replay --extra-config why3extra.test.conf sessions/drinker))))