open Elpi
open Term
open Decl
open Task
open Env
module Ctx_for_why_simple_term = Term.Ctx_for_why_simple_term
module Ctx_for_ctx_for_term = Term.Ctx_for_ctx_for_term

(* Accumulate declarations from Elpi PPX here *)
let declaration : Elpi.API.BuiltIn.declaration list = !Ty.declaration @ !Term.declaration @ !Task.declaration
let why3_builtin_declarations = Builtins.why3_builtin_declarations

(* Add a declaration to the list *)
let term = Term.term
let vsymbol = Term.vsymbol
let lsymbol = Term.lsymbol
let context_made_of_ctx_for_term = Term.context_made_of_ctx_for_term
type ctx_for_term = Term.ctx_for_term
let ctx_for_term = Term.ctx_for_term
let prsymbol = Decl.prsymbol
let decl = Decl.decl
let task = Task.task
let env = Task.env
let ty = Ty.ty

let in_ctx_for_term = Term.in_ctx_for_why_simple_term
let pp_ctx_for_term = Term.pp_ctx_for_term
let in_ctx_for_ty = Ty.in_ctx_for_why_simple_ty

let document builtins =
  let w3lp_builtins = API.BuiltIn.declare ~file_name:"w3lp.elpi" builtins
  in let header = "%% API for manipulating Why3 terms and declaration via λProlog\n%% This file is automatically generated."
  in API.BuiltIn.document_file ~header w3lp_builtins
(* Add a declaration to the list *)