open Elpi
include Term
include Decl
include Task
module Ctx_for_why_simple_term = Term.Ctx_for_why_simple_term
module Ctx_for_ctx_for_term = Term.Ctx_for_ctx_for_term
module Ctx_for_ctx_for_lsymbol = Term.Ctx_for_ctx_for_lsymbol

(* Accumulate declarations from Elpi PPX here *)
let declaration : Elpi.API.BuiltIn.declaration list =
  !Ty.declaration @ !Term.declaration @ !Task.declaration

let why3_builtin_declarations = Builtins.why3_builtin_declarations
let tdecl = Theory.tdecl
let ty = Ty.ty

let symbol_to_gref = function
  | Why3.Args_wrapper.Tstysymbol ts -> Decl.Gty ts
  | Why3.Args_wrapper.Tsprsymbol pr -> Decl.Gpr pr
  | Why3.Args_wrapper.Tslsymbol ls -> Decl.Gls ls

let document builtins =
  let w3lp_builtins = API.BuiltIn.declare ~file_name:"w3lp.elpi" builtins in
  let header =
    "%% API for manipulating Why3 terms and declaration via λProlog\n\
     %% This file is automatically generated."
  in
  API.BuiltIn.document_file ~header w3lp_builtins

(* Runtime: ELPI program loading and query execution *)

let _debug_no_typecheck =
  Why3.Debug.register_flag ~desc:"Disable typechecking for Elpi transformations"
    "no_elpi_tc"

let cached_program : (string * API.Setup.elpi * API.Compile.program) option ref
    =
  ref None

let extra_builtin_declarations : API.BuiltIn.declaration list ref = ref []

let register_builtin_declaration decl =
  extra_builtin_declarations := decl :: !extra_builtin_declarations;
  cached_program := None

let elpi_builtins () =
  let builtins =
    declaration @ why3_builtin_declarations
    @ List.rev !extra_builtin_declarations
  in
  document builtins;
  [ API.BuiltIn.declare ~file_name:"builtins.elpi"
      (builtins @ Builtin.std_declarations)
  ]

let get_program ~file =
  let file =
    let candidates = [ file; Filename.concat ".." file ] in
    match List.find_opt Sys.file_exists candidates with
    | Some path -> path
    | None -> file
  in
  match !cached_program with
  | Some (cached_file, elpi, prog) when cached_file = file -> (elpi, prog)
  | _ ->
    let elpi =
      API.Setup.init ?quotations:None ~builtins:(elpi_builtins ())
        ~file_resolver:(API.Parse.std_resolver ~paths:[] ())
        ()
    in
    let ast = API.Parse.program ~elpi ~files:[ file ] in
    let prog = API.Compile.program ~elpi [ ast ] in
    cached_program := Some (file, elpi, prog);
    (elpi, prog)

let read_output_tasks conv state output_term =
  try
    let _st, tm, _eg =
      (Elpi_api_compat.BuiltInContextualData.list conv).readback ~depth:0 []
        API.RawData.no_constraints state output_term
    in
    Format.printf "elpi: success\n%!";
    tm
  with exn ->
    (* Attemtping some useful debug prints before failing *)
    Format.eprintf "elpi: output readback failed: %s\n%!"
      (Printexc.to_string exn);
    Format.eprintf "elpi: output raw term: %a\n%!" (API.RawPp.term 0)
      output_term;
    (try
       let rec collect_list_terms ~depth tm =
         match API.RawData.look ~depth tm with
         | API.RawData.Nil -> []
         | API.RawData.Cons (hd, tl) -> hd :: collect_list_terms ~depth tl
         | _ -> failwith "not a proper list term"
       in
       List.iteri
         (fun i task_tm ->
           try
             let _ =
               conv.readback ~depth:0 [] API.RawData.no_constraints state
                 task_tm
             in
             ()
           with task_exn ->
             Format.eprintf "elpi: failing transformed task at index %d: %s\n%!"
               i
               (Printexc.to_string task_exn);
             Format.eprintf "elpi: failing transformed task raw:@. %a\n%!"
               (API.RawPp.term 0) task_tm)
         (collect_list_terms ~depth:0 output_term)
     with Failure s -> Format.eprintf "elpi: %s@." s);
    raise exn

let declare_external_symbol ~name ~ty =
  register_builtin_declaration
    (API.BuiltIn.LPCode (Printf.sprintf "external symbol %s : %s." name ty));
  API.RawData.Constants.declare_global_symbol name

let transform_query ~file build_query (t : Why3.Task.task) =
  let _elpi, prog = get_program ~file in
  match split_focused_goal t with
  | None ->
    Why3.Loc.errorm "elpi: transform interface requires a task with a goal"
  | Some (rest, goal) -> (
    let build_query state =
      let depth = 0 in
      let state, rest_t, eg1 =
        (Elpi_api_compat.BuiltInContextualData.list Theory.tdecl).embed ~depth
          [] Elpi.API.RawData.no_constraints state rest
      in
      let state, goal_t, eg2 =
        focused_goal.embed ~depth [] Elpi.API.RawData.no_constraints state goal
      in
      let state, output_uvar =
        Elpi.API.FlexibleData.Elpi.make ~name:"Output" state
      in
      let output_t = Elpi.API.RawData.mkUnifVar output_uvar ~args:[] state in
      let state, query_term, eg3 =
        build_query ~depth state rest_t goal_t output_t
      in
      (state, query_term, eg1 @ eg2 @ eg3)
    in
    let main_query = API.RawQuery.compile_raw_term prog build_query in
    match API.Execute.once (API.Compile.optimize main_query) with
    | API.Execute.Success { assignments; state; _ } ->
      let output_term = API.Data.StrMap.find "Output" assignments in
      read_output_tasks focused_task state output_term
    | Failure -> Why3.Loc.errorm "elpi: failure"
    | NoMoreSteps -> assert false)

let build_transform_with_embedded_args ~file ~entrypoint embeds =
  let build_query ~depth state rest_t goal_t output_t =
    let state, args_t, egs =
      List.fold_left
        (fun (state, args_t, egs) embed ->
          let state, arg_t, eg = embed ~depth state in
          (state, arg_t :: args_t, egs @ eg))
        (state, [], []) embeds
    in
    let query_term =
      Elpi.API.RawData.mkAppGlobalL entrypoint
        (List.rev_append args_t [ rest_t; goal_t; output_t ])
    in
    (state, query_term, egs)
  in
  Why3.Trans.store (transform_query ~file build_query)

let register_transform (type a b) ~name ~file ~entrypoint
    ~(arg_type : (a, b) Why3.Args_wrapper.trans_typ) ~desc =
  let open Why3.Args_wrapper in
  match arg_type with
  | Ttrans_l ->
    Why3.Trans.register_transform_l ~desc name
      (build_transform_with_embedded_args ~file ~entrypoint [])
  | Tenvtrans_l ->
    Why3.Trans.register_env_transform_l ~desc name (fun _env ->
        build_transform_with_embedded_args ~file ~entrypoint [])
  | _ ->
    let embed_one conv v ~depth state =
      conv.API.ContextualConversion.embed ~depth [] API.RawData.no_constraints
        state v
    in
    let embed_list conv vs ~depth state =
      (Elpi_api_compat.BuiltInContextualData.list conv).embed ~depth []
        API.RawData.no_constraints state vs
    in
    let rec make : type a b.
           acc:
             (   depth:int
              -> API.Data.state
              -> API.Data.state * API.Data.term * API.Conversion.extra_goal list)
             list
        -> (a, b) trans_typ
        -> a =
     fun ~acc -> function
       | Ttrans_l ->
         build_transform_with_embedded_args ~file ~entrypoint (List.rev acc)
       | Tenvtrans_l ->
         fun _env ->
           build_transform_with_embedded_args ~file ~entrypoint (List.rev acc)
       | Ttrans ->
         failwith
           "build_and_register_transform_with_args: Ttrans not supported (use \
            Ttrans_l)"
       | Tenvtrans ->
         fun _env ->
           failwith
             "build_and_register_transform_with_args: Tenvtrans not supported \
              (use Tenvtrans_l)"
       | Tprsymbol t -> fun v -> make ~acc:(embed_one prsymbol v :: acc) t
       | Tterm t -> fun v -> make ~acc:(embed_one term v :: acc) t
       | Tformula t -> fun v -> make ~acc:(embed_one term v :: acc) t
       | Tlsymbol t -> fun v -> make ~acc:(embed_one lsymbol v :: acc) t
       | Tty t -> fun v -> make ~acc:(embed_one ty v :: acc) t
       | Tint t ->
         fun v ->
           make
             ~acc:(embed_one Elpi_api_compat.BuiltInContextualData.int v :: acc)
             t
       | Tstring t ->
         fun v ->
           make
             ~acc:
               (embed_one Elpi_api_compat.BuiltInContextualData.string v :: acc)
             t
       | Tprlist t -> fun vs -> make ~acc:(embed_list prsymbol vs :: acc) t
       | Ttermlist t -> fun vs -> make ~acc:(embed_list term vs :: acc) t
       | Ttermlist_same (_, t) ->
         fun vs -> make ~acc:(embed_list term vs :: acc) t
       | Tidentlist t ->
         fun vs ->
           make
             ~acc:
               (embed_list Elpi_api_compat.BuiltInContextualData.string vs
               :: acc)
             t
       | Topt (_, Ttermlist t) ->
         fun v ->
           make ~acc:(embed_list term (Option.value ~default:[] v) :: acc) t
       | Topt (_, Ttermlist_same (_, t)) ->
         fun v ->
           make ~acc:(embed_list term (Option.value ~default:[] v) :: acc) t
       | Topt (_, Tprlist t) ->
         fun v ->
           make ~acc:(embed_list prsymbol (Option.value ~default:[] v) :: acc) t
       | Topt (_, Tidentlist t) ->
         fun v ->
           make
             ~acc:
               (embed_list Elpi_api_compat.BuiltInContextualData.string
                  (Option.value ~default:[] v)
               :: acc)
             t
       | Topt (s, _) ->
         fun _ ->
           failwith
             ("build_and_register_transform_with_args: Topt \"" ^ s
            ^ "\" unsupported inner type")
       | Toptbool (_, t) ->
         fun b ->
           make
             ~acc:(embed_one Elpi_api_compat.BuiltInContextualData.bool b :: acc)
             t
       | Ttysymbol t -> fun v -> make ~acc:(embed_one Ty.tysymbol v :: acc) t
       | Tsymbol t ->
         fun v -> make ~acc:(embed_one gref (symbol_to_gref v) :: acc) t
       | Tlist t ->
         fun vs ->
           make ~acc:(embed_list gref (List.map symbol_to_gref vs) :: acc) t
       | Ttheory t -> fun v -> make ~acc:(embed_one Theory.theory v :: acc) t
    in
    let make_trans = make ~acc:[] arg_type in
    Why3.Args_wrapper.wrap_and_register ~desc name arg_type make_trans
