open Elpi
include Term
include Decl
include Task
open Env
module Ctx_for_why_simple_term = Term.Ctx_for_why_simple_term
module Ctx_for_ctx_for_term = Term.Ctx_for_ctx_for_term
module Ctx_for_ctx_for_lsymbol = Term.Ctx_for_ctx_for_lsymbol

(* Accumulate declarations from Elpi PPX here *)
let declaration : Elpi.API.BuiltIn.declaration list =
  !Ty.declaration @ !Term.declaration @ !Task.declaration

let why3_builtin_declarations = Builtins.why3_builtin_declarations
let in_ctx_for_term = Term.in_ctx_for_why_simple_term
let in_ctx_for_ty = Ty.in_ctx_for_why_simple_ty
let tdecl = Theory.tdecl
let ty = Ty.ty

let document builtins =
  let w3lp_builtins = API.BuiltIn.declare ~file_name:"w3lp.elpi" builtins in
  let header =
    "%% API for manipulating Why3 terms and declaration via λProlog\n\
     %% This file is automatically generated."
  in
  API.BuiltIn.document_file ~header w3lp_builtins

(* Runtime: ELPI program loading and query execution *)

let _debug_no_typecheck =
  Why3.Debug.register_flag ~desc:"Disable typechecking for Elpi transformations"
    "no_elpi_tc"

let cached_program : (string * API.Setup.elpi * API.Compile.program) option ref
    =
  ref None

let extra_builtin_declarations : API.BuiltIn.declaration list ref = ref []

let register_builtin_declaration decl =
  extra_builtin_declarations := decl :: !extra_builtin_declarations;
  cached_program := None

let elpi_builtins () =
  let builtins =
    declaration @ why3_builtin_declarations
    @ List.rev !extra_builtin_declarations
  in
  document builtins;
  [ API.BuiltIn.declare ~file_name:"builtins.elpi"
      (builtins @ Builtin.std_declarations)
  ]

let get_program ~file =
  let file =
    let candidates = [ file; Filename.concat ".." file ] in
    match List.find_opt Sys.file_exists candidates with
    | Some path -> path
    | None -> file
  in
  match !cached_program with
  | Some (cached_file, elpi, prog) when cached_file = file -> (elpi, prog)
  | _ ->
    let elpi =
      API.Setup.init ?quotations:None ~builtins:(elpi_builtins ())
        ~file_resolver:(API.Parse.std_resolver ~paths:[] ())
        ()
    in
    let ast = API.Parse.program ~elpi ~files:[ file ] in
    let prog = API.Compile.program ~elpi [ ast ] in
    cached_program := Some (file, elpi, prog);
    (elpi, prog)

let read_output_tasks conv state output_term =
  try
    let _st, tm, _eg =
      (Elpi_api_compat.BuiltInContextualData.list conv).readback ~depth:0 []
        API.RawData.no_constraints state output_term
    in
    Format.printf "elpi: success\n%!";
    tm
  with exn ->
    (* Attemtping some useful debug prints before failing *)
    Format.eprintf "elpi: output readback failed: %s\n%!"
      (Printexc.to_string exn);
    Format.eprintf "elpi: output raw term: %a\n%!" (API.RawPp.term 0)
      output_term;
    (try
       let rec collect_list_terms ~depth tm =
         match API.RawData.look ~depth tm with
         | API.RawData.Nil -> []
         | API.RawData.Cons (hd, tl) -> hd :: collect_list_terms ~depth tl
         | _ -> failwith "not a proper list term"
       in
       List.iteri
         (fun i task_tm ->
           try
             let _ =
               conv.readback ~depth:0 [] API.RawData.no_constraints state
                 task_tm
             in
             ()
           with task_exn ->
             Format.eprintf "elpi: failing transformed task at index %d: %s\n%!"
               i
               (Printexc.to_string task_exn);
             Format.eprintf "elpi: failing transformed task raw:@. %a\n%!"
               (API.RawPp.term 0) task_tm)
         (collect_list_terms ~depth:0 output_term)
     with Failure s -> Format.eprintf "elpi: %s@." s);
    raise exn

let declare_external_symbol ~name ~ty =
  register_builtin_declaration
    (API.BuiltIn.LPCode (Printf.sprintf "external symbol %s : %s." name ty));
  API.RawData.Constants.declare_global_symbol name

let run_query_with prog build_query output_conv =
  let main_query = API.RawQuery.compile_raw_term prog build_query in
  match API.Execute.once (API.Compile.optimize main_query) with
  | API.Execute.Success { assignments; state; _ } ->
    let output_term = API.Data.StrMap.find "Output" assignments in
    Some (read_output_tasks output_conv state output_term)
  | Failure -> None
  | NoMoreSteps -> assert false
