name: CI
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout tree
      uses: actions/checkout@v4
    - name: Set up OCaml
      uses: ocaml/setup-ocaml@v2.1.7
      with:
        ocaml-compiler: 5.1.x
        dune-cache: true
    - name: Build
      run: opam install why3_elpi
