name: CI
on:
  push:
    branches: [ main, ppx-elpi ]
  workflow_dispatch:
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout tree
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v17

      - name: Setup Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@v13
        with:
          use-flakehub: false

      - name: Check formatting
        run: nix fmt -- --ci

      - name: Build
        run: nix develop .#default --command dune build

      - name: Test
        run: nix develop .#default --command dune runtest

      - name: Replay sessions
        run: nix develop .#default --command dune build @tests/replay
