name: CI
on:
  push:
    branches: [ main, ppx-elpi ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout tree
      uses: actions/checkout@v4
    - name: Set up OCaml
      uses: ocaml/setup-ocaml@v2.1.7
      with:
        ocaml-compiler: 4.13.1
        dune-cache: true
    - name: Build
      run: |
        opam install . --deps-only
        opam exec -- dune build
    - name: Test
      run: opam exec -- why3 prove -D why3 --extra-config why3extra.conf ./tests/simple.mlw -a "lp nop"
